workflow:
    - publish

shared:
    image: node:6

jobs:
    main:
        steps:
            - restart-pr-from-fork: echo yay!

    publish:
        steps:
            - install: npm install semantic-release
            - publish: npm run semantic-release
        secrets:
            # Publishing to NPM
            - NPM_TOKEN
            # Pushing tags to Git
            - GH_TOKEN
